estrangeiros/urls.py
from django.urls import path
from . import views
app_name = 'es'
urlpatterns = [
    path('', views.v_estrangeiros, name='pg_inicial'),
    path('acao/', views.v_est_acao, name='acao'),
    path('comedia/', views.v_est_comedia, name='comedia'),
    path('documentario/', views.v_est_documentario, name='documentario'),
    path('drama/', views.v_est_drama, name='drama'),
    path('terror/', views.v_est_terror, name='terror'),
    path('<str:genero>/<str:titulo>', views.v_est_detalhamento , name='detalhes')
    
]

home/urls.py
from django.urls import path
from . import views

app_name = 'hm'
urlpatterns = [
    path('', views.v_home, name='home'),
]

nacionais/urls.py
from django.urls import path
from . import views
app_name = 'nac'
urlpatterns = [
    path('', views.v_nacionais, name='pg_inicial'),
    path('acao/', views.v_nac_acao, name='acao'),
    path('comedia/', views.v_nac_comedia, name='comedia'),
    path('documentario/', views.v_nac_documentario, name='documentario'),
    path('drama/', views.v_nac_drama, name='drama'),
    path('terror/', views.v_nac_terror, name='terror'),
    path('<str:genero>/<str:titulo>', views.v_nac_detalhamento , name='detalhes')
    
]

sinopse/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('estrangeiros/', include('estrangeiros.urls')),
    path('nacionais/', include('nacionais.urls')),

]

estrangeiros/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

nacionais/models.py
from django.db import models

# Create your models here.

estrangeiros/views.py
from django.shortcuts import render
from utilidades.opcoes.fabrica import falsos

DADOS = [falsos() for _ in range(50)]
dados = {'todos': DADOS}

# Create your views here.
def v_estrangeiros(request):
    global dados
    return render(request, 'estrangeiros/paginas/estrangeiros.html',context=dados)

def v_est_acao(request):
    return render(request, 'estrangeiros/paginas/acao.html', context=dados)

def v_est_comedia(request):
    return render(request, 'estrangeiros/paginas/comedia.html', context=dados)

def v_est_documentario(request):
    return render(request, 'estrangeiros/paginas/documentario.html', context=dados)

def v_est_drama(request):
    return render(request, 'estrangeiros/paginas/drama.html', context=dados)

def v_est_terror(request):
    return render(request, 'estrangeiros/paginas/terror.html', context=dados)

def v_est_detalhamento(request, genero, titulo):
    resultado = {}
    for item in dados['todos']:
        # if item['origem'] == 'Filme Estrangeiro':
        #     print('\n\n\n',item['titulo'], '\n\n\n',item['origem'], '\n\n\n', titulo)     
            if item['titulo'] == titulo:
                print('oi')
                resultado = item         
                break
    return render(request, 'estrangeiros/paginas/detalhes.html', context= resultado )

home/views.py
from django.shortcuts import render

# Create your views here.

def v_home(request):
    return render(request, 'home/paginas/home.html')

nacionais/views.py
from django.shortcuts import render
from utilidades.opcoes.fabrica import falsos

DADOS = [falsos() for _ in range(50)]
dados = {'todos': DADOS}

# Create your views here.
def v_nacionais(request):
    global dados
    return render(request, 'nacionais/paginas/nacionais.html',context=dados)

def v_nac_acao(request):
    return render(request, 'nacionais/paginas/acao.html', context=dados)

def v_nac_comedia(request):
    return render(request, 'nacionais/paginas/comedia.html', context=dados)

def v_nac_documentario(request):
    return render(request, 'nacionais/paginas/documentario.html', context=dados)

def v_nac_drama(request):
    return render(request, 'nacionais/paginas/drama.html', context=dados)

def v_nac_terror(request):
    return render(request, 'nacionais/paginas/terror.html', context=dados)

def v_nac_detalhamento(request, genero, titulo):
    resultado = {}
    for item in dados['todos']:    
            if item['titulo'] == titulo:
                resultado = item         
                break
            else:
                 resultado = {'msg':'Infelizmente, este filme não está presente em nosso catálogo'}
    return render(request, 'nacionais/paginas/detalhes.html', context= resultado )

estrangeiros/templates/estrangeiros/paginas/acao.html
{% extends 'global/paginas/base_inicio.html' %}
{% load static %}

{% block css_app %}
<link rel="stylesheet" href="{% static 'estrangeiros/css/estilos.css' %}">;
{% endblock css_app %}


{% block titulo_app %} 
{% include 'estrangeiros/parciais/head.html' %} 
{% endblock titulo_app %}

{% block menu_app %}
{% include 'estrangeiros/parciais/menu.html' %}
{% endblock menu_app %}


{% block tabela_app %}
    {% for item in todos %}
    {% if item.origem == 'Filme Estrangeiro' %}
    {% if item.genero == 'Ação' %}
    {% include 'estrangeiros/parciais/tabela.html' %}
    {% endif %}
    {% endif %}
    {% endfor %}
{% endblock tabela_app %}

estrangeiros/templates/estrangeiros/paginas/comedia.html
{% extends 'global/paginas/base_inicio.html' %}
{% load static %}

{% block css_app %}
<link rel="stylesheet" href="{% static 'estrangeiros/css/estilos.css' %}">;
{% endblock css_app %}


{% block titulo_app %} 
{% include 'estrangeiros/parciais/head.html' %} 
{% endblock titulo_app %}

{% block menu_app %}
{% include 'estrangeiros/parciais/menu.html' %}
{% endblock menu_app %}


{% block tabela_app %}
    {% for item in todos %}
    {% if item.origem == 'Filme Estrangeiro' %}
    {% if item.genero == 'Comédia' %}
    {% include 'estrangeiros/parciais/tabela.html' %}
    {% endif %}
    {% endif %}
    {% endfor %}
{% endblock tabela_app %}

estrangeiros/templates/estrangeiros/paginas/detalhes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{titulo}}</title>
</head>
<body>
    <h1>Detalhamento do Filme</h1>

    <iframe width="550" height="325" 
            src="https://www.youtube.com/watch?v=OY9A3vubQM0" 
            title="Vídeo YouTube" >
    </iframe>
        <ul>
            <li>
                <h2>Título</h2>
                <p>{{titulo}}</p>           
            
            <li>
                <h2>Origem</h2>
                <p>{{origem}}</p>
            </li>
            
            <li>
                <h2>Gênero</h2>
                <p>{{genero}}</p>
            </li>
            
            <li>
                <h2>Lançamento</h2>
                <p>{{data}}</p>
            </li>
            
            <li>
                <h2>Diretor</h2>
                <p>{{diretor.nome}} {{diretor.sobrenome}}</p>
            </li>
            
            <li>
                <h2>Resenha</h2>
                <p>{{descricao}}</p>
            </li>
           
        </ul>
</body>
</html> 

estrangeiros/templates/estrangeiros/paginas/documentario.html
{% extends 'global/paginas/base_inicio.html' %}
{% load static %}

{% block css_app %}
<link rel="stylesheet" href="{% static 'estrangeiros/css/estilos.css' %}">;
{% endblock css_app %}


{% block titulo_app %} 
{% include 'estrangeiros/parciais/head.html' %} 
{% endblock titulo_app %}

{% block menu_app %}
{% include 'estrangeiros/parciais/menu.html' %}
{% endblock menu_app %}


{% block tabela_app %}
    {% for item in todos %}
    {% if item.origem == 'Filme Estrangeiro' %}
    {% if item.genero == 'Documentário' %}
    {% include 'estrangeiros/parciais/tabela.html' %}
    {% endif %}
    {% endif %}
    {% endfor %}
{% endblock tabela_app %}

estrangeiros/templates/estrangeiros/paginas/drama.html
{% extends 'global/paginas/base_inicio.html' %}
{% load static %}

{% block css_app %}
<link rel="stylesheet" href="{% static 'estrangeiros/css/estilos.css' %}">;
{% endblock css_app %}


{% block titulo_app %} 
{% include 'estrangeiros/parciais/head.html' %} 
{% endblock titulo_app %}

{% block menu_app %}
{% include 'estrangeiros/parciais/menu.html' %}
{% endblock menu_app %}


{% block tabela_app %}
    {% for item in todos %}
    {% if item.origem == 'Filme Estrangeiro' %}
    {% if item.genero == 'Drama' %}
    {% include 'estrangeiros/parciais/tabela.html' %}
    {% endif %}
    {% endif %}
    {% endfor %}
{% endblock tabela_app %}

estrangeiros/templates/estrangeiros/paginas/estrangeiros.html
{% extends 'global/paginas/base_inicio.html' %}
{% load static %}

{% block css_app %}
<link rel="stylesheet" href="{% static 'estrangeiros/css/estilos.css' %}">
{% endblock css_app %}


{% block head_app %} 
{% include 'estrangeiros/parciais/head.html' %} 
{% endblock head_app %}

{% block menu_app %}
{% include 'estrangeiros/parciais/menu.html' %} 
{% endblock menu_app %}


{% block tabela_app %}
    {% for item in todos %}
    {% if item.origem == 'Filme Estrangeiro' %}
    {% include 'estrangeiros/parciais/tabela.html' %}
    {% endif %}
    {% endfor %}
{% endblock tabela_app %}

estrangeiros/templates/estrangeiros/paginas/terror.html
{% extends 'global/paginas/base_inicio.html' %}
{% load static %}

{% block css_app %}
<link rel="stylesheet" href="{% static 'estrangeiros/css/estilos.css' %}">;
{% endblock css_app %}


{% block titulo_app %} 
{% include 'estrangeiros/parciais/head.html' %} 
{% endblock titulo_app %}

{% block menu_app %}
{% include 'estrangeiros/parciais/menu.html' %}
{% endblock menu_app %}


{% block tabela_app %}
    {% for item in todos %}
    {% if item.origem == 'Filme Estrangeiro' %}
    {% if item.genero == 'Terror' %}
    {% include 'estrangeiros/parciais/tabela.html' %}
    {% endif %}
    {% endif %}
    {% endfor %}
{% endblock tabela_app %}

estrangeiros/templates/estrangeiros/parciais/head.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ESTRANGEIROS</title>
</head>

estrangeiros/templates/estrangeiros/parciais/menu.html
<div class="menu_est">
    <ul>
        <li><a href="{% url 'hm:home' %}">HOME</a></li>
        <li><a href="{% url 'es:acao' %}">AÇÃO</a></li>
        <li><a href="{% url 'es:comedia' %}">COMÉDIA</a></li>
        <li><a href="{% url 'es:documentario' %}">DOCUMENTÁRIO</a></li>
        <li><a href="{% url 'es:drama' %}">DRAMA</a></li>
        <li><a href="{% url 'es:terror' %}">TERROR</a></li>
        <li><a href="{% url 'nac:pg_inicial' %}">NACIONAIS</a></li>

    </ul>
</div>

estrangeiros/templates/estrangeiros/parciais/tabela.html
{% load static %}
<table class="tabela">
    <tr>
        <th >
            <a href="{% url 'es:detalhes' item.genero item.titulo %}">
            <img src="{{item.imagem.url}}" width="200px"></th>
           </a>

        <th>
            <p> <strong>{{item.origem}}</strong></p> 
            <p> Titulo: <strong>{{item.titulo}}</strong> </p> 
            <p> Gênero: <strong>{{item.genero}}</strong> </p>
            <p> Lançamento: <strong>{{item.data}}</strong> </p> 
            <p> Diretor:<strong> {{item.diretor.nome}}</strong> <strong>{{item.diretor.sobrenome}}</strong> </p> 
        </th>
    </tr>  
     <tr >
        <td colspan="2" >Lorem ipsum dolor sit amet consectetur adipisicing elit. Id, aliquam iusto architecto praesentium labore dolor quaerat voluptate suscipit incidunt aspernatur quod minus voluptatum pariatur? Assumenda, libero quas! Odio, officiis expedita?</p> 
        </td>
    </tr>
</table>

home/templates/home/paginas/home.html
{% extends 'global/paginas/base_inicio.html' %}
{% load static %}

{% block css_app %}
<link rel="stylesheet" href="{% static 'home/css/estilos.css' %}">
{% endblock css_app %}  

{% block head_app %} 
{% include 'home/parciais/head.html' %} 
{% endblock head_app %} 

{% block imagem_cinema %}
   {% include 'home/parciais/img.html' %} 
{% endblock imagem_cinema %}

home/templates/home/parciais/head.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HOME</title>
</head>

home/templates/home/parciais/img.html
{% load static %}


<div class="imag_home">
    <a href="{% url 'es:pg_inicial' %}" style="text-decoration: none;"> <h2>ESTRANGEIROS</h2>
    <img src="{% static 'home/images/cinema_estrangeiro.png'%}"  class="imagem" >
    </a>
    <a href="{% url 'nac:pg_inicial' %}" style="text-decoration: none; "> <h2 style="color: green;">NACIONAIS</h2>
    <img src="{% static 'home/images/imagem_nacional.webp' %}" class="imagem" >
     </a>
</div>
    

home/templates/home/parciais/menu.html
{% comment %} <div class='menu'>
    <ul>
        <li><a href="{% url 'es:pg_inicial' %}">FILME ESTRANGEIRO</a></li>
        <li><a href="{% url 'es:pg_inicial' %}">FILME NACIONAL</a></li>
    </ul>
</div> {% endcomment %}

nacionais/templates/nacionais/paginas/acao.html
{% extends 'global/paginas/base_inicio.html' %}
{% load static %}

{% block css_app %}
<link rel="stylesheet" href="{% static 'nacionais/css/estilos.css' %}">;
{% endblock css_app %}


{% block titulo_app %} 
{% include 'nacionais/parciais/head.html' %} 
{% endblock titulo_app %}

{% block menu_app %}
{% include 'nacionais/parciais/menu.html' %}
{% endblock menu_app %}


{% block tabela_app %}
    {% for item in todos %}
    {% if item.origem == 'Filme Nacional' %}
    {% if item.genero == 'Ação' %}
    {% include 'nacionais/parciais/tabela.html' %}
    {% endif %}
    {% endif %}
    {% endfor %}
{% endblock tabela_app %}

nacionais/templates/nacionais/paginas/comedia.html
{% extends 'global/paginas/base_inicio.html' %}
{% load static %}

{% block css_app %}
<link rel="stylesheet" href="{% static 'nacionais/css/estilos.css' %}">;
{% endblock css_app %}


{% block titulo_app %} 
{% include 'nacionais/parciais/head.html' %} 
{% endblock titulo_app %}

{% block menu_app %}
{% include 'nacionais/parciais/menu.html' %}
{% endblock menu_app %}


{% block tabela_app %}
    {% for item in todos %}
    {% if item.origem == 'Filme Nacional' %}
    {% if item.genero == 'Comédia' %}
    {% include 'nacionais/parciais/tabela.html' %}
    {% endif %}
    {% endif %}
    {% endfor %}
{% endblock tabela_app %}

nacionais/templates/nacionais/paginas/detalhes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{titulo}}</title>
</head>
<body>
    <h1>Detalhamento do Filme</h1>

    <iframe width="550" height="325" 
            src="https://www.youtube.com/watch?v=OY9A3vubQM0" 
            title="Vídeo YouTube" >
    </iframe>

       
        <ul>
            <li>
                <h2>Título</h2>
                <p>{{titulo}}</p>           
            
            <li>
                <h2>Origem</h2>
                <p>{{origem}}</p>
            </li>
            
            <li>
                <h2>Gênero</h2>
                <p>{{genero}}</p>
            </li>
            
            <li>
                <h2>Lançamento</h2>
                <p>{{data}}</p>
            </li>
            
            <li>
                <h2>Diretor</h2>
                <p>{{diretor.nome}} {{diretor.sobrenome}}</p>
            </li>
            
            <li>
                <h2>Resenha</h2>
                <p>{{descricao}}</p>
            </li>
           
        </ul>
    

</body>
</html> 

nacionais/templates/nacionais/paginas/documentario.html
{% extends 'global/paginas/base_inicio.html' %}
{% load static %}

{% block css_app %}
<link rel="stylesheet" href="{% static 'nacionais/css/estilos.css' %}">;
{% endblock css_app %}


{% block titulo_app %} 
{% include 'nacionais/parciais/head.html' %} 
{% endblock titulo_app %}

{% block menu_app %}
{% include 'nacionais/parciais/menu.html' %}
{% endblock menu_app %}


{% block tabela_app %}
    {% for item in todos %}
    {% if item.origem == 'Filme Nacional' %}
    {% if item.genero == 'Documentário' %}
    {% include 'nacionais/parciais/tabela.html' %}
    {% endif %}
    {% endif %}
    {% endfor %}
{% endblock tabela_app %}

nacionais/templates/nacionais/paginas/drama.html
{% extends 'global/paginas/base_inicio.html' %}
{% load static %}

{% block css_app %}
<link rel="stylesheet" href="{% static 'nacionais/css/estilos.css' %}">;
{% endblock css_app %}


{% block titulo_app %} 
{% include 'nacionais/parciais/head.html' %} 
{% endblock titulo_app %}

{% block menu_app %}
{% include 'nacionais/parciais/menu.html' %}
{% endblock menu_app %}


{% block tabela_app %}
    {% for item in todos %}
    {% if item.origem == 'Filme Nacional' %}
    {% if item.genero == 'Drama' %}
    {% include 'nacionais/parciais/tabela.html' %}
    {% endif %}
    {% endif %}
    {% endfor %}
{% endblock tabela_app %}

nacionais/templates/nacionais/paginas/nacionais.html
{% extends 'global/paginas/base_inicio.html' %}
{% load static %}

{% block css_app %}
<link rel="stylesheet" href="{% static 'nacionais/css/estilos.css' %}">
{% endblock css_app %}


{% block head_app %} 
{% include 'nacionais/parciais/head.html' %} 
{% endblock head_app %}

{% block menu_app %}
{% include 'nacionais/parciais/menu.html' %} 
{% endblock menu_app %}


{% block tabela_app %}
    {% for item in todos %}
    {% if item.origem == 'Filme Nacional' %}
    {% include 'nacionais/parciais/tabela.html' %}
    {% endif %}
    {% endfor %}
{% endblock tabela_app %}

nacionais/templates/nacionais/paginas/terror.html
{% extends 'global/paginas/base_inicio.html' %}
{% load static %}

{% block css_app %}
<link rel="stylesheet" href="{% static 'nacionais/css/estilos.css' %}">;
{% endblock css_app %}


{% block titulo_app %} 
{% include 'nacionais/parciais/head.html' %} 
{% endblock titulo_app %}

{% block menu_app %}
{% include 'nacionais/parciais/menu.html' %}
{% endblock menu_app %}


{% block tabela_app %}
    {% for item in todos %}
    {% if item.origem == 'Filme Nacional' %}
    {% if item.genero == 'Terror' %}
    {% include 'nacionais/parciais/tabela.html' %}
    {% endif %}
    {% endif %}
    {% endfor %}
{% endblock tabela_app %}

nacionais/templates/nacionais/parciais/head.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NACIONAIS</title>
</head>

nacionais/templates/nacionais/parciais/menu.html
<div class="menu_est">
    <ul>
        <li><a href="{% url 'hm:home' %}">HOME</a></li>
        <li><a href="{% url 'nac:acao' %}">AÇÃO</a></li>
        <li><a href="{% url 'nac:comedia' %}">COMÉDIA</a></li>
        <li><a href="{% url 'nac:documentario' %}">DOCUMENTÁRIO</a></li>
        <li><a href="{% url 'nac:drama' %}">DRAMA</a></li>
        <li><a href="{% url 'nac:terror' %}">TERROR</a></li>
        <li><a href="{% url 'es:pg_inicial' %}">ESTRANGEIROS</a></li>

    </ul>
</div>

nacionais/templates/nacionais/parciais/tabela.html
{% load static %}
<table class="tabela">
    <tr>
        <th >
            <a href="{% url 'nac:detalhes' item.genero item.titulo %}">
            <img src="{{item.imagem.url}}" width="200px"></th>
           </a>

        <th>
            <p> <strong>{{item.origem}}</strong></p> 
            <p> Titulo: <strong>{{item.titulo}}</strong> </p> 
            <p> Gênero: <strong>{{item.genero}}</strong> </p>
            <p> Lançamento: <strong>{{item.data}}</strong> </p> 
            <p> Diretor:<strong> {{item.diretor.nome}}</strong> <strong>{{item.diretor.sobrenome}}</strong> </p> 
        </th>
    </tr>  
     <tr >
        <td colspan="2" >Lorem ipsum dolor sit amet consectetur adipisicing elit. Id, aliquam iusto architecto praesentium labore dolor quaerat voluptate suscipit incidunt aspernatur quod minus voluptatum pariatur? Assumenda, libero quas! Odio, officiis expedita?</p> 
        </td>
    </tr>
</table>